select count(*) as Admins from Admins 
select count(*) as Aracs from Aracs
select count(*) as Cuzdans from Cuzdans
select count(*) as iletisims from iletisims
select count(*) as Kampanyalars from Kampanyalars
select count(*) as Kullanicilars from Kullanicilars
select count(*) as MutfakKategoris from MutfakKategoris
select count(*) as OtelKategoris from OtelKategoris
select count(*) as Otels from Otels
select count(*) as Restorans from Restorans
select count(*) as RezervasyonAracs from RezervasyonAracs
select count(*) as RezervasyonOtels from RezervasyonOtels
select count(*) as RezervasyonRestorans from RezervasyonRestorans
select count(*) as RezervasyonTurs from RezervasyonTurs
select count(*) as RezervasyonUcaks from RezervasyonUcaks
select count(*) as Sehirs from Sehirs
select count(*) as TurKategoris from TurKategoris
select count(*) as Turs from Turs
select count(*) as Ucaks from Ucaks
select count(*) as ülke from ülke
select count(*) as YakitKategoris from YakitKategoris
select count(*) as YorumlarARACs from YorumlarARACs
select count(*) as YorumlarRESTORANs from YorumlarRESTORANs
select count(*) as Yorumlars from Yorumlars
select count(*) as YorumlarTURs from YorumlarTURs