INSERT INTO [dbo].[iletisims]
           ([AdSoyad]
           ,[Mail]
           ,[Konu]
           ,[Mesaj])
VALUES
('Ahmed Faruk Dilmaç', 'ahmed@gmail.com', 'Rezervasyon Problemi', 'Rezervasyon iþlemi sýrasýnda bir hata ile karþýlaþtým, destek talep ediyorum.'),
('Pelin Özkan', 'Pelin183@gmail.com', 'Rezervasyon Onayý', 'Rezervasyon onayýmý alamadým, kontrol edebilir misiniz?'),
('Pelin Karaca', 'Pelin631@hotmail.c', 'Ödeme Sorunu', 'Ödeme iþlemim baþarýsýz oldu, yardýmcý olabilir misiniz?'),
('Cenk Özdemir', 'Cenk782@hotmail.c', 'Üyelik Sorunu', 'Üyelik oluþturamýyorum, lütfen kontrol edin.'),
('Can Çetin', 'Can202@gmail.com', 'Hizmet Kalitesi', 'Rezervasyon sürecindeki hizmet kalitesinden memnun kalmadým.'),
('Oðuz Tanrýverdi', 'Oðuz688@hotmail.c', 'Fatura Talebi', 'Faturamý temin etmek istiyorum, yardýmcý olabilir misiniz?'),
('Tolga Aksoy', 'Tolga257@hotmail.c', 'Yeni Rezervasyon', 'Yeni bir rezervasyon oluþturmak istiyorum, detaylý bilgi verebilir misiniz?'),
('Selim Turan', 'Selim580@gmail.com', 'Kampanya Sorgusu', 'Güncel kampanyalarýnýz hakkýnda bilgi almak istiyorum.'),
('Hüseyin Avcý', 'Hüseyin912@gmail.com', 'Uygulama Sorunu', 'Uygulamanýzda teknik bir sorun yaþýyorum, destek talep ediyorum.'),
('Sinem Gül', 'Sinem790@hotmail.c', 'Rezervasyon Ýptali', 'Rezervasyonumu iptal etmek istiyorum, nasýl bir yol izlemeliyim?'),
('Umut Yaman', 'Umut669@gmail.com', 'Ödeme Onayý', 'Ödeme onayýný almadým, lütfen destek olun.'),
('Pelin Ünal', 'Pelin115@hotmail.c', 'Kampanya Bilgisi', 'Rezervasyon kampanyalarýnýzdan nasýl yararlanabilirim?'),
('Ahmet Altýn', 'Ahmet659@gmail.com', 'Rezervasyon Durumu', 'Rezervasyon durumumu öðrenmek istiyorum.'),
('Ahmet Turan', 'Ahmet556@gmail.com', 'Destek Talebi', 'Rezervasyon ile ilgili genel bir sorum var.'),
('Tuðçe Gül', 'Tuðçe135@hotmail.c', 'Teknik Sorun', 'Sitenizde teknik bir hata ile karþýlaþtým.'),
('Hande Ünal', 'Hande985@hotmail.c', 'Rezervasyon Ýptali', 'Rezervasyonumu iptal etmek istiyorum.'),
('Onur Avcý', 'Onur100@hotmail.c', 'Hizmet Kalitesi', 'Rezervasyon süreci ile ilgili genel bir þikayetim var.'),
('Barýþ Karaca', 'Barýþ333@hotmail.c', 'Yeni Rezervasyon', 'Yeni bir rezervasyon yapmak istiyorum.'),
('Arda Yaman', 'Arda772@gmail.com', 'Ödeme Problemi', 'Ödeme sýrasýnda bir hata aldým.'),
('Rüya Aydýn', 'Rüya816@gmail.com', 'Bilgilendirme Talebi', 'Hizmetleriniz hakkýnda genel bilgi almak istiyorum.'),
('Ece Arýkan', 'Ece407@hotmail.c', 'Rezervasyon Sorunu', 'Rezervasyon yaparken bir hata oluþtu.'),
('Arzu Keskin', 'Arzu708@gmail.com', 'Destek Talebi', 'Genel bir rezervasyon sorunu ile ilgili yardým almak istiyorum.'),
('Çaðla Güneþ', 'Çaðla170@gmail.com', 'Fiyat Bilgisi', 'Rezervasyon fiyatlarýnýz hakkýnda bilgi almak istiyorum.'),
('Ýrem Þahin', 'Ýrem968@gmail.com', 'Kampanya Sorusu', 'Devam eden kampanyalarýnýz var mý?'),
('Emel Bozkurt', 'Emel224@hotmail.c', 'Teknik Sorun', 'Sitenizde bir hata ile karþýlaþtým, destek talep ediyorum.'),
('Merve Arslan', 'Merve817@hotmail.c', 'Üyelik Sorunu', 'Üyelik oluþturamýyorum.'),
('Yiðit Ülgen', 'Yiðit736@hotmail.c', 'Rezervasyon Güncelleme', 'Rezervasyonumu güncellemek istiyorum.'),
('Esra Aydýn', 'Esra528@gmail.com', 'Bilgi Talebi', 'Rezervasyon detaylarý hakkýnda bilgi alabilir miyim?'),
('Pelin Avcý', 'Pelin306@gmail.com', 'Yeni Rezervasyon', 'Yeni bir rezervasyon yapmak istiyorum, lütfen yardýmcý olun.'),
('Esra Arýkan', 'Esra407@gmail.com', 'Rezervasyon Ýptali', 'Mevcut rezervasyonumu iptal etmek istiyorum.'),
('Elif Arýkan', 'Elif892@gmail.com', 'Ödeme Problemi', 'Ödeme sýrasýnda sorun yaþadým.'),
('Ece Tekin', 'Ece348@gmail.com', 'Fatura Talebi', 'Ödeme sonrasý fatura almak istiyorum.'),
('Esra Altýn', 'Esra267@gmail.com', 'Destek Talebi', 'Rezervasyonla ilgili genel bir destek talebim var.'),
('Furkan Kýlýç', 'Furkan441@hotmail.c', 'Kampanya Bilgisi', 'Güncel kampanyalarýnýz hakkýnda bilgi almak istiyorum.'),
('Arda Öztürk', 'Arda900@gmail.com', 'Ödeme Sorunu', 'Ödeme iþlemim baþarýsýz oldu.'),
('Can Uzun', 'Can127@gmail.com', 'Hizmet Kalitesi', 'Süreçle ilgili genel bir þikayetim var.'),
('Beril Köseoðlu', 'Beril511@hotmail.c', 'Yeni Rezervasyon', 'Yeni bir rezervasyon yapmak istiyorum.'),
('Ýrem Tekin', 'Ýrem949@gmail.com', 'Teknik Sorun', 'Sitenizde teknik bir hata aldým.'),
('Melis Ünal', 'Melis362@hotmail.c', 'Rezervasyon Durumu', 'Mevcut rezervasyon durumumu öðrenmek istiyorum.'),
('Oðuz Turan', 'Oðuz915@gmail.com', 'Rezervasyon Ýptali', 'Rezervasyonumu iptal etmek istiyorum.'),
('Ali Saðlam', 'Ali317@hotmail.c', 'Bilgi Talebi', 'Rezervasyonlar hakkýnda genel bilgi almak istiyorum.'),
('Melis Turan', 'Melis786@gmail.com', 'Kampanya Bilgisi', 'Devam eden kampanyalarýnýz hakkýnda bilgi almak istiyorum.'),
('Kerem Demir', 'Kerem803@hotmail.c', 'Ödeme Problemi', 'Ödeme iþlemi sýrasýnda bir sorun yaþadým.'),
('Elif Avcý', 'Elif104@gmail.com', 'Rezervasyon Sorunu', 'Rezervasyon iþlemi sýrasýnda hata aldým.'),
('Ahmet Korkmaz', 'Ahmet897@hotmail.c', 'Hizmet Kalitesi', 'Rezervasyon süreciyle ilgili bir þikayetim var.'),
('Arda Ünal', 'Arda661@gmail.com', 'Yeni Rezervasyon', 'Yeni bir rezervasyon yapmak istiyorum.'),
('Selim Gül', 'Selim207@hotmail.c', 'Kampanya Sorgusu', 'Güncel kampanyalarýnýzý öðrenmek istiyorum.'),
('Gizem Koç', 'Gizem305@gmail.com', 'Destek Talebi', 'Rezervasyonla ilgili genel destek talebim var.'),
('Arzu Kaya', 'Arzu350@gmail.com', 'Rezervasyon Durumu', 'Rezervasyon durumumu öðrenmek istiyorum.'),
('Derya Ülgen', 'Derya523@gmail.com', 'Ödeme Sorunu', 'Ödeme iþlemi sýrasýnda hata aldým.'),
('Yiðit Güneþ', 'Yiðit153@hotmail.c', 'Teknik Sorun', 'Sitenizde karþýlaþtýðým bir hata hakkýnda yardým almak istiyorum.'),
('Derya Arýkan', 'Derya206@hotmail.c', 'Rezervasyon Güncelleme', 'Rezervasyonumu güncellemek istiyorum.'),
('Barýþ Karaca', 'Barýþ460@hotmail.c', 'Bilgilendirme Talebi', 'Rezervasyon süreciniz hakkýnda bilgi almak istiyorum.'),
('Elif Çolak', 'Elif551@gmail.com', 'Fatura Talebi', 'Ödeme sonrasý fatura talep ediyorum.'),
('Eren Baþar', 'Eren474@hotmail.c', 'Kampanya Bilgisi', 'Rezervasyon kampanyalarýnýzdan yararlanmak istiyorum.'),
('Mehmet Korkmaz', 'Mehmet263@gmail.com', 'Rezervasyon Sorunu', 'Rezervasyon yaparken bir hata aldým.'),
('Burak Bozkurt', 'Burak235@hotmail.c', 'Destek Talebi', 'Genel bir rezervasyon sorunum var.'),
('Tuðçe Þahin', 'Tuðçe361@gmail.com', 'Üyelik Sorunu', 'Üyelik oluþtururken sorun yaþýyorum.'),
('Arda Turan', 'Arda907@gmail.com', 'Rezervasyon Ýptali', 'Rezervasyonumu iptal etmek istiyorum.'),
('Gizem Soylu', 'Gizem493@gmail.com', 'Bilgilendirme Talebi', 'Rezervasyon hakkýnda genel bilgi almak istiyorum.'),
('Derya Özkan', 'Derya353@gmail.com', 'Fatura Talebi', 'Ödeme sonrasý faturamý almak istiyorum.'),
('Ýrem Doðan', 'Ýrem847@gmail.com', 'Yeni Rezervasyon', 'Yeni bir rezervasyon yapmak istiyorum.'),
('Gizem Güneþ', 'Gizem990@hotmail.c', 'Kampanya Sorusu', 'Devam eden kampanyalarýnýz var mý?'),
('Ýrem Sezer', 'Ýrem873@gmail.com', 'Ödeme Sorunu', 'Ödeme sýrasýnda teknik bir hata aldým.'),
('Melis Koç', 'Melis503@gmail.com', 'Rezervasyon Güncelleme', 'Rezervasyon bilgilerimi güncellemek istiyorum.'),
('Melih Sezer', 'Melih866@hotmail.c', 'Rezervasyon Durumu', 'Rezervasyon durumumu öðrenmek istiyorum.'),
('Burak Akyüz', 'Burak211@gmail.com', 'Destek Talebi', 'Rezervasyonla ilgili genel bir destek talep ediyorum.'),
('Çaðla Altýn', 'Çaðla457@hotmail.c', 'Hizmet Kalitesi', 'Rezervasyon sürecindeki hizmet kalitesinden memnun kalmadým.'),
('Umut Tanrýverdi', 'Umut750@hotmail.c', 'Fiyat Bilgisi', 'Rezervasyon fiyatlarýnýz hakkýnda bilgi almak istiyorum.'),
('Ceren Çelik', 'Ceren891@gmail.com', 'Rezervasyon Sorunu', 'Rezervasyon yaparken bir sorunla karþýlaþtým.'),
('Rüya Soylu', 'Rüya996@gmail.com', 'Kampanya Sorgusu', 'Rezervasyon kampanyalarýnýz hakkýnda bilgi almak istiyorum.'),
('Arzu Yýldýz', 'Arzu489@hotmail.c', 'Destek Talebi', 'Rezervasyon sürecinde karþýlaþtýðým bir sorun için destek istiyorum.'),
('Beril Arýkan', 'Beril998@gmail.com', 'Ödeme Problemi', 'Ödeme iþlemi sýrasýnda bir hata aldým.'),
('Emre Kýlýç', 'Emre979@gmail.com', 'Rezervasyon Durumu', 'Rezervasyonumun mevcut durumunu öðrenmek istiyorum.'),
('Arda Güneþ', 'Arda389@hotmail.c', 'Üyelik Sorunu', 'Üyelik oluþturamýyorum, lütfen yardýmcý olun.'),
('Doða Avcý', 'Doða721@hotmail.c', 'Yeni Rezervasyon', 'Yeni bir rezervasyon yapmak istiyorum, destek talep ediyorum.'),
('Hande Çelik', 'Hande697@hotmail.c', 'Teknik Sorun', 'Sitenizde teknik bir hata ile karþýlaþtým.'),
('Burak Kýlýç', 'Burak165@hotmail.c', 'Bilgi Talebi', 'Rezervasyon fiyatlarýnýz hakkýnda bilgi almak istiyorum.'),
('Zeynep Koç', 'Zeynep169@gmail.com', 'Fatura Talebi', 'Fatura talep ediyorum.'),
('Ece Ünal', 'Ece948@gmail.com', 'Rezervasyon Güncelleme', 'Rezervasyon bilgilerimi güncellemek istiyorum.'),
('Oðuz Köseoðlu', 'Oðuz354@hotmail.c', 'Kampanya Bilgisi', 'Güncel kampanyalarýnýz hakkýnda bilgi almak istiyorum.'),
('Ali Kýlýç', 'Ali989@hotmail.c', 'Rezervasyon Problemi', 'Rezervasyon iþlemi sýrasýnda hata aldým.'),
('Beril Kaya', 'Beril122@hotmail.c', 'Ödeme Sorunu', 'Ödeme iþlemi tamamlanmadý, lütfen kontrol edin.'),
('Cem Çetin', 'Cem512@hotmail.c', 'Yeni Rezervasyon', 'Rezervasyon yapmak istiyorum, yardýmcý olur musunuz?'),
('Zeynep Kaya', 'Zeynep929@hotmail.c', 'Hizmet Kalitesi', 'Hizmet süreciyle ilgili bir þikayetim var.'),
('Ezgi Keskin', 'Ezgi465@gmail.com', 'Rezervasyon Sorunu', 'Rezervasyon yaparken bir hata aldým.'),
('Rüya Saðlam', 'Rüya240@gmail.com', 'Kampanya Sorgusu', 'Güncel kampanyalarýnýz hakkýnda bilgi almak istiyorum.'),
('Mehmet Avcý', 'Mehmet567@hotmail.c', 'Teknik Sorun', 'Sitenizde teknik bir hata ile karþýlaþtým, destek talep ediyorum.'),
('Ayþe Kaya', 'Ayþe400@gmail.com', 'Rezervasyon Ýptali', 'Rezervasyonumu iptal etmek istiyorum.'),
('Ahmet Tekin', 'Ahmet698@gmail.com', 'Fatura Talebi', 'Ödeme sonrasý fatura almak istiyorum.'),
('Oðuz Þahin', 'Oðuz651@gmail.com', 'Rezervasyon Güncelleme', 'Rezervasyonumu güncellemek istiyorum.'),
('Burak Yýldýz', 'Burak722@gmail.com', 'Destek Talebi', 'Genel bir rezervasyon sorunum var.'),
('Gül Ülgen', 'Gül799@hotmail.c', 'Kampanya Bilgisi', 'Rezervasyon kampanyalarýnýz hakkýnda bilgi almak istiyorum.'),
('Buse Doðan', 'Buse377@gmail.com', 'Hizmet Kalitesi', 'Hizmet sürecinizden memnun kalmadým, þikayetim var.'),
('Beril Eren', 'Beril403@gmail.com', 'Rezervasyon Problemi', 'Rezervasyon iþlemi sýrasýnda hata aldým.'),
('Yiðit Özkan', 'Yiðit414@gmail.com', 'Yeni Rezervasyon', 'Yeni bir rezervasyon yapmak istiyorum, lütfen destek olun.'),
('Ece Özdemir', 'Ece169@hotmail.c', 'Fatura Talebi', 'Ödeme sonrasý faturamý almak istiyorum.'),
('Pelin Karaca', 'Pelin153@hotmail.c', 'Bilgilendirme Talebi', 'Rezervasyon süreciniz hakkýnda bilgi almak istiyorum.'),
('Ali Ülgen', 'Ali550@gmail.com', 'Ödeme Sorunu', 'Ödeme sýrasýnda sorun yaþadým, destek talep ediyorum.'),
('Eren Bulut', 'Eren161@gmail.com', 'Rezervasyon Durumu', 'Rezervasyonumun durumunu öðrenmek istiyorum.');