INSERT INTO [dbo].[iletisims] ([AdSoyad], [Mail], [Konu], [Mesaj])
VALUES
('Ella Anderson', 'Ella834@gmail.com', 'Reservation Inquiry', 'Hello, I would like to know more details about the booking process and available dates.'),
('Camila Walker', 'Camila328@hotmail.c', 'Payment Issue', 'Hi, I am facing an issue with the payment gateway while booking a reservation.'),
('Michael Maxwell', 'Michael458@gmail.com', 'Cancelation Policy', 'Could you please provide information on the cancellation policy for reservations?'),
('Leo Ramsey', 'Leo378@hotmail.c', 'Booking Confirmation', 'I need confirmation for my booking made yesterday. Could you assist?'),
('Aiden Baker', 'Aiden881@hotmail.c', 'Room Availability', 'Can you check if there are rooms available for the next weekend?'),
('Mason Brooks', 'Mason416@gmail.com', 'Discount Inquiry', 'Are there any discounts available for group reservations?'),
('Ella Griffin', 'Ella356@gmail.com', 'Website Navigation Issue', 'I am having trouble navigating the website while trying to book a reservation.'),
('Liam Hale', 'Liam229@hotmail.c', 'Payment Refund', 'I would like to request a refund for a cancelled reservation.'),
('Hannah Kennedy', 'Hannah824@gmail.com', 'Room Preferences', 'Can I specify my preferences for a room during the reservation process?'),
('Alexander Shepherd', 'Alexander629@gmail.com', 'Loyalty Program', 'Do you offer any loyalty programs for frequent bookings?'),
('Evelyn Hughes', 'Evelyn363@hotmail.c', 'Reservation Details', 'Could you send me the details for my recent reservation?'),
('Jacob Parker', 'Jacob843@hotmail.c', 'Special Request', 'Is it possible to request a late check-out during booking?'),
('Grace Turner', 'Grace251@gmail.com', 'Support Assistance', 'I need help with updating my booking details.'),
('Ryan Clark', 'Ryan524@gmail.com', 'Check-in Process', 'Can you explain the check-in process for online reservations?'),
('Aria Bennett', 'Aria806@gmail.com', 'Booking History', 'Can I access my past bookings on your website?'),
('Mason Baker', 'Mason172@gmail.com', 'Promotional Offers', 'Are there any ongoing promotional offers for bookings?'),
('Amelia Turner', 'Amelia831@gmail.com', 'Error in Booking', 'I encountered an error while booking. Can you assist me in resolving it?'),
('Madison Parker', 'Madison124@gmail.com', 'Reservation Amendment', 'I would like to amend the dates for my current reservation.'),
('Ava Mitchell', 'Ava768@hotmail.c', 'Extra Services', 'Do you offer any additional services like airport pickups?'),
('Mateo Evans', 'Mateo815@gmail.com', 'Group Booking Inquiry', 'Can you provide details on group booking options?'),
('Camila Fisher', 'Camila410@hotmail.c', 'Reservation Modification', 'I need to modify the number of people in my booking. Can you assist?'),
('Layla Duncan', 'Layla778@gmail.com', 'Hotel Amenities', 'Can you provide more details on the amenities available in your rooms?'),
('Zoe Garrett', 'Zoe478@hotmail.c', 'Reservation Confirmation', 'Could you confirm my reservation for next month?'),
('Aria Knight', 'Aria780@hotmail.c', 'Booking Payment', 'I have completed my booking but there is an issue with the payment transaction.'),
('Abigail Hughes', 'Abigail981@gmail.com', 'Late Check-In', 'Is it possible to check-in later than the regular hours due to my late flight?'),
('Sophie Foster', 'Sophie769@gmail.com', 'Travel Restrictions', 'Are there any travel restrictions or requirements I should be aware of when booking?'),
('Benjamin Jenkins', 'Benjamin408@hotmail.c', 'Booking Assistance', 'Can I get assistance with making a booking for a special event?'),
('Harper Garrett', 'Harper119@gmail.com', 'Availability Inquiry', 'Could you let me know if there are rooms available for the summer season?'),
('Jacob Walker', 'Jacob995@hotmail.c', 'Early Check-in Request', 'I would like to request an early check-in for my upcoming reservation.'),
('Hannah Duncan', 'Hannah167@gmail.com', 'Booking Confirmation', 'Could you please confirm the booking made for me a few days ago?'),
('James Whitney', 'James522@hotmail.c', 'Refund Inquiry', 'I have recently canceled a booking. Can you let me know when I will receive my refund?'),
('Layla Newton', 'Layla514@gmail.com', 'Loyalty Points', 'How can I use my loyalty points when booking a new reservation?'),
('Liam Walker', 'Liam213@gmail.com', 'Group Reservation', 'Can you provide more information about booking a group reservation for an event?'),
('Abigail Ramsey', 'Abigail326@gmail.com', 'Payment Issues', 'I am experiencing issues with the payment options for my reservation.'),
('Luna Sanders', 'Luna138@gmail.com', 'Booking Help', 'Could you provide assistance in completing my reservation online?'),
('Benjamin Sanders', 'Benjamin125@gmail.com', 'Booking Questions', 'I have some questions about the booking process. Can you help me?'),
('Aiden Kennedy', 'Aiden342@gmail.com', 'Add Extra Guests', 'Can I add additional guests to my existing reservation?'),
('Olivia Turner', 'Olivia624@gmail.com', 'Upgrade Inquiry', 'I would like to inquire about room upgrades for my booking.'),
('Aiden Spencer', 'Aiden959@hotmail.c', 'Room Rate', 'Can you provide me with more information on your room rates and deals?'),
('Oliver Young', 'Oliver596@hotmail.c', 'Booking Confirmation', 'Can I get a confirmation email for the booking I just made?'),
('Ethan Gibson', 'Ethan909@gmail.com', 'Booking Error', 'I received an error while completing my booking. Can you help resolve this?'),
('Mason Foster', 'Mason558@gmail.com', 'Discount Inquiry', 'Are there any ongoing promotions or discounts for new users?'),
('Harper Nash', 'Harper569@hotmail.c', 'Cancellation Request', 'I would like to cancel my reservation. Can you guide me through the process?'),
('Amelia Walker', 'Amelia206@hotmail.c', 'Special Offer', 'Are there any special offers for returning customers?'),
('Abigail Diaz', 'Abigail977@hotmail.c', 'Booking Assistance', 'I need help with selecting the best dates for booking.'),
('Sophie Knight', 'Sophie967@hotmail.c', 'Hotel Facilities', 'Can you provide more information about the hotel facilities during my stay?'),
('Luna Mitchell', 'Luna520@gmail.com', 'Payment Confirmation', 'Could you confirm if my payment for the reservation has been received?'),
('Victoria Anderson', 'Victoria763@gmail.com', 'Booking Inquiry', 'I have a few questions regarding booking a family room.'),
('Leo Hale', 'Leo253@hotmail.c', 'Special Requests', 'I have special requests for my stay. How can I inform you about them?'),
('Michael Bennett', 'Michael677@hotmail.c', 'Booking Details', 'Could you send me the detailed information of my recent booking?'),
('Ryan Lawson', 'Ryan388@gmail.com', 'Booking Options', 'I am interested in knowing the booking options available for next weekend.'),
('Mia Hale', 'Mia202@hotmail.c', 'Room Availability', 'Could you confirm if there are rooms available for the upcoming holiday weekend?'),
('Zara Foster', 'Zara493@gmail.com', 'Room Upgrade', 'Is it possible to upgrade my room for a better view?'),
('Emily Carter', 'Emily305@gmail.com', 'Booking Assistance', 'I need assistance with selecting the right room for my stay.'),
('Ella Anderson', 'Ella614@hotmail.c', 'Booking Confirmation', 'I would like to confirm my booking details and check-in time.'),
('Leo Bennett', 'Leo766@hotmail.c', 'Cancellation Request', 'I would like to cancel my reservation due to unforeseen circumstances.'),
('Mateo Turner', 'Mateo880@gmail.com', 'Booking Status', 'Can you provide me with the status of my reservation?'),
('Logan Bennett', 'Logan865@gmail.com', 'Reservation Questions', 'I have some questions regarding the reservation process, can you assist me?'),
('Ellie Turner', 'Ellie232@gmail.com', 'Availability Check', 'Can you confirm if there are rooms available for my requested dates?'),
('Ella Anderson', 'Ella504@gmail.com', 'Refund Process', 'Could you guide me through the refund process for my cancellation request?'),
('Olivia Garrett', 'Olivia840@gmail.com', 'Booking Inquiry', 'I am looking to make a reservation for the upcoming season. Could you help me?'),
('Scarlett Spencer', 'Scarlett164@gmail.com', 'Cancellation Inquiry', 'I need information regarding the cancellation policy for my booking.'),
('Zoe Patton', 'Zoe435@gmail.com', 'Booking Confirmation', 'Can you confirm that my booking has been successfully processed?'),
('Aria Duncan', 'Aria396@gmail.com', 'Check-in Questions', 'I need help understanding the check-in process and requirements.'),
('Jacob Griffin', 'Jacob362@hotmail.c', 'Payment Query', 'Could you clarify the payment methods accepted for reservations?'),
('Leo Brooks', 'Leo613@gmail.com', 'Booking Cancellation', 'I would like to cancel my booking. Could you assist me with this?'),
('Emily Hale', 'Emily937@hotmail.c', 'Booking Assistance', 'I need assistance with booking a room for a family of four.'),
('Oliver Walker', 'Oliver499@hotmail.c', 'Booking Issue', 'I encountered an issue while trying to complete my reservation.'),
('Camila Ramsey', 'Camila256@hotmail.c', 'Refund Request', 'I would like to inquire about the refund process for a booking cancellation.'),
('Ella Patton', 'Ella196@hotmail.c', 'Reservation Change', 'Can I change the dates for my reservation at no extra cost?'),
('Chloe Carter', 'Chloe428@hotmail.c', 'Booking Process', 'Can you help me with the steps to finalize my booking?'),
('Scarlett Jackson', 'Scarlett554@gmail.com', 'Cancellation Policy', 'Could you explain your cancellation policy in detail?'),
('Scarlett Knight', 'Scarlett371@hotmail.c', 'Special Offer Inquiry', 'Are there any special offers or discounts available for this month?'),
('Aurora Taylor', 'Aurora472@gmail.com', 'Reservation Status', 'Can you confirm the status of my reservation?'),
('Sophie Walker', 'Sophie893@hotmail.c', 'Booking Help', 'I need help completing my reservation and choosing the right dates.'),
('Logan Fisher', 'Logan882@hotmail.c', 'Room Preferences', 'Can I request specific preferences for my room at the time of booking?'),
('Harper Tate', 'Harper901@hotmail.c', 'Early Check-In', 'Is it possible to check in early before the official check-in time?'),
('Lily Wheeler', 'Lily364@hotmail.c', 'Late Check-Out', 'Can I request a late check-out for my upcoming stay?'),
('Ava Young', 'Ava924@gmail.com', 'Group Booking', 'I am interested in booking for a group. Can you provide me with more details?'),
('Mateo Walker', 'Mateo601@gmail.com', 'Room Availability', 'Could you confirm if rooms are available for my preferred dates?'),
('Layla Reed', 'Layla398@hotmail.c', 'Upgrade Inquiry', 'Is it possible to upgrade to a premium room during booking?'),
('Chloe Foster', 'Chloe340@hotmail.c', 'Payment Assistance', 'I need assistance with completing my payment for a recent reservation.'),
('Aurora Parker', 'Aurora213@gmail.com', 'Booking Details', 'Could you send me more details about the room types available for booking?'),
('Mila Lambert', 'Mila480@gmail.com', 'Late Check-In', 'I will be arriving late for my check-in. Is that a problem?'),
('Isabella Lambert', 'Isabella864@gmail.com', 'Booking Support', 'I need help with booking a room for two adults and a child.'),
('Sophie Parker', 'Sophie159@hotmail.c', 'Booking Confirmation', 'Could you confirm my reservation and send me the details?'),
('Zoe Lawson', 'Zoe208@gmail.com', 'Special Request', 'I would like to request a room with a balcony for my stay.'),
('Mila Harrison', 'Mila821@hotmail.c', 'Payment Issue', 'I am encountering an issue with my payment for a recent booking.'),
('Victoria Taylor', 'Victoria496@gmail.com', 'Booking Assistance', 'Can you help me with the booking process for a family trip?'),
('Jacob Clark', 'Jacob734@gmail.com', 'Confirmation Request', 'Could you confirm the dates and details of my reservation?'),
('Harper Jenkins', 'Harper428@gmail.com', 'Cancellation Inquiry', 'I would like to inquire about the cancellation policy for my booking.'),
('Olivia Wheeler', 'Olivia862@hotmail.c', 'Booking Inquiry', 'Could you assist me with booking a room for next month?'),
('Zoe Knight', 'Zoe967@gmail.com', 'Booking Request', 'I would like to make a reservation for the upcoming weekend.'),
('Camila Bennett', 'Camila832@hotmail.c', 'Refund Status', 'Could you check the status of my refund request?'),
('Scarlett Lawson', 'Scarlett975@hotmail.c', 'Booking Cancellation', 'I would like to cancel my reservation due to unexpected changes in plans.'),
('Mason Hale', 'Mason663@hotmail.c', 'Late Check-Out Request', 'Can I request a late check-out for my upcoming stay?'),
('James Reed', 'James358@gmail.com', 'Reservation Query', 'I need clarification on the dates available for booking.'),
('Emily Jackson', 'Emily670@gmail.com', 'Booking Assistance', 'I need help completing my booking for the upcoming holiday season.'),
('Henry Reed', 'Henry660@hotmail.c', 'Check-in Clarification', 'Could you clarify the process for checking in at the hotel?'),
('Lucas Knight', 'Lucas666@hotmail.c', 'Special Requests', 'I have special requests for my room. How can I add them during booking?'),
('Ellie Whitney', 'Ellie659@hotmail.c', 'Booking Help', 'I need help booking a room for a specific event date.');