INSERT INTO Kampanyalars (Ad)  
VALUES  
('%15 Ýlkbahar Fýrsatý'),  
('%25 Yaz Ýndirimi'),  
('%35 Sonbahar Avantajý'),  
('Uzun Konaklamalara Özel Kampanya'),  
('Ailece Tatil Fýrsatý'),  
('Hafta Sonu Kaçamaðý Ýndirimi'),  
('Sonbahar Tatil Fýrsatý'),  
('Yýlýn En Büyük Ýndirimi'),  
('Sezon Sonu Kaçýrýlmayacak Fýrsat'),  
('Hafta Ýçi Rezervasyon Avantajý'),  
('Arkadaþlarla Tatil Kampanyasý'),  
('Erken Planlama Ýndirimi'),  
('Her Þey Dahil Tatil Fýrsatý'),  
('%45 Büyük Tatil Kampanyasý'),  
('Dönemsel Tatil Ýndirimi'),  
('Ekstra Gün Hediyesi'),  
('Þimdi Al Sonra Öde Kampanyasý'),  
('Haftalýk Özel Ýndirim'),  
('%50 Tatil Kaçamaðý Avantajý'),  
('Yaz Sezonuna Özel Avantaj'),
('4 Gece Kal 3 Gece Öde'),  
('Ýkinci Kiþi %50 Ýndirimli'),  
('Ailelere Özel Ýndirim'),  
('Tatil Paketi Kampanyasý'),  
('Sonbahar Ýndirimi'),  
('Yýlbaþý Özel Fýrsatý'),  
('7 Geceye Özel Ýndirim'),  
('Balayý Çiftlerine Avantaj'),  
('Gruplara Ekstra Fýrsat'),  
('Sadýk Müþteri Kampanyasý'),  
('Son Dakika Fýrsatý'),  
('Yaz Tatili Ýndirimi'),  
('Kýþ Kaçamaðý Kampanyasý'),  
('Her Þey Dahil Avantaj');  